### ISSUE TITLE
Infrastructure

### ISSUE THREAD

**Issue by cw-roy** [cw-roy/team-nfi-capstone#2]
### Basic requirements:
- Created via a CloudFormation template or Terraform
### Advanced ideas:
- CFT stack has outputs for accessing services
- CFT stack created via ansible playbook
### From the lab instructions:
- Make sure Ansible and Docker are both installed on our AWS Workstations
-

**Comment by curtis-roy** [comment]
CloudFormation template functional (Venkata / Curtis)

**Comment by curtis-roy** [comment]
Ansible playbooks built to setup/create Docker container for Bamboo

**Comment by curtis-roy** [comment]
Spun up secondary stack for testing

**Comment by cw-roy** [comment]
Issue closed
