### ISSUE TITLE
CI / CD pipeline

### ISSUE THREAD

**Issue by cw-roy** [cw-roy/team-nfi-capstone#23]
### Basic Requirements
- Create pipeline that deploys Wordpress to production
- CI pipeline for testing pyblog and building its Docker image

### Advanced Ideas:
- Create a pipeline to provision and configure Staging and Prod servers from scratch
- pyblog docker image versioning strategy (:v1, :v2, etc) for "cutting a release"

**Comment by curtis-roy** [comment]
12/8/2022:  Bamboo pipeline is building and testing pyblog at this time.  Further updates TBD.
