### ISSUE TITLE
Infrastructure Monitoring

### ISSUE THREAD

**Issue by cw-roy** [cw-roy/team-nfi-capstone#41]
### Basic Requirements:
- Basic Bamboo and Server metrics tracked
### Advanced ideas:
- Monitoring agents deployed via Ansible

**Comment by curtis-roy** [comment]
12/08/2022:  Prod server metrics are being tracked.

Bamboo metrics TBD.

**Comment by cw-roy** [comment]
Issue closed

**Comment by cw-roy** [comment]
Closing; last comment didn't take
