### ISSUE TITLE
PyBlog Client

### ISSUE THREAD

**Issue by cw-roy** [cw-roy/team-nfi-capstone#9]
### Basic Requirements:
- Show latest blog post
- Upload a blog post
- Unittest coverage > 80%
- Dockerized

 'docker run pyblog read'

### Advanced Ideas / Additional features:
-Add comment to blog post
-Edit existing post
-Search for post by keywords

**Comment by curtis-roy** [comment]
3 of 4 basic requirements met:
- Show latest blog post
- Upload a blog post
- Dockerized

Static analysis testing is functional.  Unittest coverage stats TBD.
